# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e8a3a565d7373214c6165126ab9ba22f6dfa2a0d93f5dc3ee7d57c606ff0c1fd768d3283cbb900a3457ad0c532f028b38f7dd52b06fac31195ae0708ca10b4af

test:
  secret_key_base: f800209c98e2163b5c2ca5106953a634078a900d151faf818fcee852955722ebfa9c46941190b2b92612b4ac2344d25c9a85a660911fe539316c77fdad2f10df

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
